title: Oluwajoba's Portfolio
description: "Welcome to my personal website showcasing my skills, projects, and experiences."
logo: assets/Images/image.png
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

